### ISSUE TITLE
xmlデータのdb登録

### ISSUE THREAD

**Issue by mjtakenon** [mjtakenon/noritubusi-map#1]
* クライアント側で情報(駅/路線)を読み込むためにサーバーに置くデータベースを作成する必要がある
* dbを作成しやすくするためのxmlの前処理
  * Curve.xmlには駅と駅間が両方線分として登録されている
  * これを駅(点)と駅間(線分)に変換したい

**Comment by popunbom** [comment]
駅名で検索をかけることが想定されているのなら、Elasticsearch などの全文検索対応のDBがいいと思います。

**Comment by popunbom** [comment]
最低限のことができたので、一度 Close します。
