### ISSUE TITLE
GItlab に移行したい

### ISSUE THREAD

**Issue by popunbom** [mjtakenon/noritubusi-map#10]
## 目的

CI/CD や Issue 管理など、Github にない機能が Gitlab 側には備わっているため、「開発の間」は Gitlab を利用したい。

## メリット

- Issue ・進捗管理が楽
  - Board 機能
  - Graph 機能

- CI/CD 機能がデフォルトで搭載
  - 将来的にWeb アプリケーションとしてクラウド上にデプロイするのであれば、CDは利用したい(利用してみたい)
 
## デメリット

- Web サイト自体のレスポンスが遅い
- #8 で言及した 大容量ファイルを扱う機構がない
- アカウントの作成が必要になる
  - Github のアカウントでログインすることも可能
- Github 上にリポジトリを集約することができなくなる
  - 完成したら、プロジェクトごと Gitlab から Github へ移管することができる
  -  コミット履歴などを残したまま移行することも可能

**Comment by mjtakenon** [comment]
試しにあっちに作ってみました、ご査収ください。
