### ISSUE TITLE
駅のプロット(仮)

### ISSUE THREAD

**Issue by mjtakenon** [mjtakenon/noritubusi-map#2]
#1 
* xlsxに駅名・緯度経度などをまとめたので一度マップにプロットしてみたい
* 同名別路線の駅は別とカウントされているため統合を検討したい
  * 統合後の座標はどうするのか?重心をとるのか駅の表示サイズを変更するのか

**Comment by popunbom** [comment]
同名別路線な複雑な駅はとりあえず後回しにして、シンプルな構造になってる駅(路線)に限定して行ってみるといいと思います。

**Comment by mjtakenon** [comment]
google maps api 使って表示しようとしたらクレカ登録の上無料枠は28000リクエスト/月と変更されていた(2018年7月から)

**Comment by popunbom** [comment]
#14, #17, #19 に代替 Issue を立てたので、一旦 Close します。
