### ISSUE TITLE
[BE] 駅情報DBの見直し (同一駅名別路線の統一)

### ISSUE THREAD

**Issue by popunbom** [mjtakenon/noritubusi-map#35]
## 背景

DBから取得した駅情報をもとに地図上にピンを置く際、現状のDBスキーマの場合だと同じ駅の建物内にある別路線それぞれに1つピンが与えられ、ピンが必要以上にプロットされる。
このことにより次のような問題が発生すると考えられる。

- BE <-> FE 間での余分なデータのやり取り
- FE サイドのパフォーマンス低下

上記の事情から、駅情報DBのレコード見直し、スキーマ見直しが必要であると考えられる

## 要件

- 新たに、「路線情報一覧」が取得できるテーブルの作成

同一建物内に存在する建物は、同一レコード内に含まれている方が都合が良いが、乗りつぶし情報を構築する際には、別レコードであるほうが望ましいため、既存のものとは別に新たにテーブルを作成する必要があると考えられる。

**Comment by mjtakenon** [comment]
スキーマを新しくし、同名別路線の駅をBuildingテーブルに統合しました。
半径500mの同名駅を単純に統合するような処理になっています。
