### ISSUE TITLE
[BE] 駅名検索が機能しない

### ISSUE THREAD

**Issue by mjtakenon** [mjtakenon/noritubusi-map#50]
現在駅名検索が機能しません。(駅のプロットはされます)
データソースを変えたことで、 company_name カラムが消滅したためだと思います。
クエリを変えるだけだとは思いますが、修正お願いします。

**Comment by rain9525** [comment]
70298fd で対応しました

**Comment by popunbom** [comment]
フロント側も 502495485 の Commit で対応しました。バックエンド側の変更も確認しました。

問題なさそうなので、Close します。
