### ISSUE TITLE
[FE] リファクタリング

### ISSUE THREAD

**Issue by popunbom** [mjtakenon/noritubusi-map#66]
## 問題

- **`Map.vue` ファイルにマップ機能以外のすべての機能が書かれているため見通しが悪い**
  - 現状まだいいが、保守することを考えたらよろしくない

## 要件
- 別ファイルにコンポーネント・モジュールを切り離す
- **Vuex による状態遷移の管理**

**Comment by mjtakenon** [comment]
以降が完了しdevelopにマージされたので閉じます
