### ISSUE TITLE
[BE] API リクエスト時の Content-Type を "application/json" に統一してほしい

### ISSUE THREAD

**Issue by popunbom** [mjtakenon/noritubusi-map#67]
## 問題
- `POST /signup` などで、リクエストボディの `Content-Type` が `x-www-form-urlencode` となっており、勝手が悪い
- API 全体で、リクエストもレスポンスも `application/json` で統一してほしい

**Comment by rain9525** [comment]
@popunbom @mjtakenon 
このような形にしようと思います。意見をください。

### リクエスト
`POST /signup`での例。パスパラメータ以外のパラメータをJSONにする。
```
{
	"userid": "test",
	"password": "pass"
}
```

### レスポンス
駅データ等は既にJSONで送っているので変更なし。
リクエストの状態を返すもの(例 `/signout`)は文字列で送っているため、以下に変更する。
`status`はリクエスト結果をコードで示したものです。HTTPステータスコードとは別で、詳細なリクエスト結果を示します。
`message`は`status`に対応する詳細なメッセージを格納します。

```
{
	"status": 0,
	"message": "ok"
}
```
```
{
	"status": 2000,
	"message": "invalid parameter"
}
```

**Comment by popunbom** [comment]
👍 OKです
