### ISSUE TITLE
大容量ファイルに Git LFS を利用する

### ISSUE THREAD

**Issue by popunbom** [mjtakenon/noritubusi-map#8]
## 目的

現状、駅名データや地図データなどが素の Git で管理されているため、 clone や fetch などが遅くなっている問題がある。Git 上で大容量データを取り扱うための仕組みとして Git LFS があり、これを利用する。

## 参考リンク

- https://git-lfs.github.com/

**Comment by popunbom** [comment]
現状そこまで問題になってなさそう(？)なので、一旦保留にしたいです。

**Comment by rain9525** [comment]
`move-datasets`でGit LFS対応させました。
LFSを導入した環境でないとバグるらしいので、要検討

**Comment by rain9525** [comment]
`server`ブランチはGitLFSを利用するようにしました
